In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./데이터자료/3. 증가율 데이터 정리끝.csv", encoding='cp949') 
df_data = pd.read_csv("./데이터자료/4. 이자보상배율 데이터.csv", encoding = 'cp949')

In [3]:
df[df["회사명"]=="(주)금빛"]

,회사명,거래소코드,회계년도,상장일,상장폐지일,소속코드,산업명,매출액증가율,유형자산증가율,재고자산증가율,...,유동자산회전률,당좌자산회전률,부가가치,총자본투자효율,설비투자효율,기계투자효율,부가가치율,노동소득분배율,자본분배율,이윤분배율
171,(주)금빛,45890,2011-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,-24.64,-3.53,-57.36,...,0.75,1.49,-20171.84,-18.45,-46.14,-697.68,-35.89,0.00,0.00,0.00
172,(주)금빛,45890,2012-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,27.92,-1.04,-15.85,...,1.49,2.60,7320.90,7.45,16.92,233.27,10.18,137.85,-37.85,-86.79
173,(주)금빛,45890,2013-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,22.98,-2.39,-14.98,...,2.09,3.54,22703.29,21.84,53.79,887.90,25.68,61.47,38.53,12.74
174,(주)금빛,45890,2014-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,-6.51,0.15,27.64,...,1.86,3.13,23218.34,21.27,54.96,790.82,28.09,66.07,33.93,7.02
175,(주)금빛,45890,2015-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,2.58,-0.20,0.30,...,1.80,3.17,23668.16,21.35,56.24,832.41,27.91,63.79,36.21,12.95
176,(주)금빛,45890,2016-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,-10.77,-2.69,-13.78,...,1.63,2.74,22485.48,20.31,54.94,963.82,29.72,63.14,36.86,11.76
177,(주)금빛,45890,2017-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,-3.64,-2.67,16.97,...,1.48,2.41,16634.17,15.17,41.76,755.92,22.82,84.22,15.78,-32.44
178,(주)금빛,45890,2018-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,-27.08,37.83,-22.62,...,1.08,1.72,10254.87,9.99,18.70,595.25,19.29,139.63,-39.63,-64.80
179,(주)금빛,45890,2019-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,10.33,2.58,-23.16,...,1.43,2.18,-15590.79,-15.16,-27.96,-1381.64,-26.58,0.00,0.00,0.00
180,(주)금빛,45890,2020-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,-30.22,8.74,-51.27,...,1.00,1.28,272.56,0.22,0.45,11.12,0.67,4117.38,-4017.38,-6527.69

In [4]:
df_data[df_data["회사명"]=="(주)금빛"]

,회사명,거래소코드,회계년도,[제조]이자보상배율(이자비용)(IFRS),[제조]* (정상)영업손익(보고서기재)(IFRS),[제조] 이자비용(IFRS),[제조]이자보상배율(이자비용)(IFRS연결),[제조]* (정상)영업손익(보고서기재)(IFRS연결),[제조] 이자비용(IFRS연결)
240,(주)금빛,45890,2010/12,-3.91,-12641422.0,3232752.0,-3.33,-11185609.0,3359211.0
241,(주)금빛,45890,2011/12,-7.50,-23453022.0,3125423.0,-7.72,-28092675.0,3639472.0
242,(주)금빛,45890,2012/12,1.58,4426882.0,2802197.0,-1.49,-4298279.0,2886701.0
243,(주)금빛,45890,2013/12,1.01,3010298.0,2975097.0,1.83,5386449.0,2938524.0
244,(주)금빛,45890,2014/12,2.13,5408716.0,2537642.0,2.26,5726835.0,2537809.0
245,(주)금빛,45890,2015/12,1.85,4332701.0,2346939.0,1.82,4267123.0,2346939.0
246,(주)금빛,45890,2016/12,1.37,3137611.0,2282499.0,1.83,4166263.0,2282499.0
247,(주)금빛,45890,2017/12,-1.45,-2981646.0,2049689.0,0.03,59125.0,2049740.0
248,(주)금빛,45890,2018/12,-9.55,-18191416.0,1905525.0,-8.83,-16869325.0,1909997.0
249,(주)금빛,45890,2019/12,-4.23,-16662557.0,3938198.0,-4.07,-16108710.0,3954193.0
250,(주)금빛,45890,2020/12,-4.44,-16412470.0,3694783.0,-4.86,-18854001.0,3878491.0

In [5]:
df_data

,회사명,거래소코드,회계년도,[제조]이자보상배율(이자비용)(IFRS),[제조]* (정상)영업손익(보고서기재)(IFRS),[제조] 이자비용(IFRS),[제조]이자보상배율(이자비용)(IFRS연결),[제조]* (정상)영업손익(보고서기재)(IFRS연결),[제조] 이자비용(IFRS연결)
0,(주)CMG제약,58820,2010/12,-7.420000e+00,-7537071.0,1016039.0,-7.42,-7537071.0,1016039.0
1,(주)CMG제약,58820,2011/12,3.940000e+00,714950.0,181404.0,3.53,640283.0,181404.0
2,(주)CMG제약,58820,2012/12,-7.450000e+00,-4045140.0,542880.0,-7.75,-4205503.0,542880.0
3,(주)CMG제약,58820,2013/12,7.300000e-01,822547.0,1133753.0,0.70,791250.0,1134104.0
4,(주)CMG제약,58820,2014/12,3.630000e+00,446018.0,122840.0,3.60,442322.0,122840.0
...,...,...,...,...,...,...,...,...,...
15670,흥구석유(주),24060,2016/12,7.660000e+00,963788.0,125854.0,NaN,NaN,NaN
15671,흥구석유(주),24060,2017/12,5.910000e+00,751487.0,127191.0,NaN,NaN,NaN
15672,흥구석유(주),24060,2018/12,1.266000e+01,1092436.0,86276.0,NaN,NaN,NaN
15673,흥구석유(주),24060,2019/12,2.520200e+02,500763.0,1987.0,NaN,NaN,NaN
15674,흥구석유(주),24060,2020/12,1.000000e+09,-493797.0,0.0,NaN,NaN,NaN

In [6]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15675 entries, 0 to 15674
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   회사명                            15675 non-null  object
 1   거래소코드                          15675 non-null  int64
 2   회계년도                           15675 non-null  object
 3   [제조]이자보상배율(이자비용)(IFRS)         13374 non-null  float64
 4   [제조]* (정상)영업손익(보고서기재)(IFRS)    13574 non-null  float64
 5   [제조]   이자비용(IFRS)              13574 non-null  float64
 6   [제조]이자보상배율(이자비용)(IFRS연결)       9703 non-null   float64
 7   [제조]* (정상)영업손익(보고서기재)(IFRS연결)  9784 non-null   float64
 8   [제조]   이자비용(IFRS연결)            9784 non-null   float64
dtypes: float64(6), int64(1), object(2)
memory usage: 1.1+ MB

In [7]:
df_data.columns = df_data.columns.str.replace("   ","")

In [8]:
df_data.columns

Index(['회사명', '거래소코드', '회계년도', '[제조]이자보상배율(이자비용)(IFRS)',
       '[제조]* (정상)영업손익(보고서기재)(IFRS)', '[제조]이자비용(IFRS)',
       '[제조]이자보상배율(이자비용)(IFRS연결)', '[제조]* (정상)영업손익(보고서기재)(IFRS연결)',
       '[제조]이자비용(IFRS연결)'],
      dtype='object')

In [9]:
df_data["[제조]* (정상)영업손익(보고서기재)(IFRS연결)"] = df_data["[제조]* (정상)영업손익(보고서기재)(IFRS연결)"].fillna(df_data["[제조]* (정상)영업손익(보고서기재)(IFRS)"])  
df_data["[제조]이자비용(IFRS연결)"] = df_data["[제조]이자비용(IFRS연결)"].fillna(df_data["[제조]이자비용(IFRS)"])

In [10]:
df_data["이자보상배율"] = round(df_data["[제조]* (정상)영업손익(보고서기재)(IFRS연결)"]/df_data["[제조]이자비용(IFRS연결)"],2)
df_data

,회사명,거래소코드,회계년도,[제조]이자보상배율(이자비용)(IFRS),[제조]* (정상)영업손익(보고서기재)(IFRS),[제조]이자비용(IFRS),[제조]이자보상배율(이자비용)(IFRS연결),[제조]* (정상)영업손익(보고서기재)(IFRS연결),[제조]이자비용(IFRS연결),이자보상배율
0,(주)CMG제약,58820,2010/12,-7.420000e+00,-7537071.0,1016039.0,-7.42,-7537071.0,1016039.0,-7.42
1,(주)CMG제약,58820,2011/12,3.940000e+00,714950.0,181404.0,3.53,640283.0,181404.0,3.53
2,(주)CMG제약,58820,2012/12,-7.450000e+00,-4045140.0,542880.0,-7.75,-4205503.0,542880.0,-7.75
3,(주)CMG제약,58820,2013/12,7.300000e-01,822547.0,1133753.0,0.70,791250.0,1134104.0,0.70
4,(주)CMG제약,58820,2014/12,3.630000e+00,446018.0,122840.0,3.60,442322.0,122840.0,3.60
...,...,...,...,...,...,...,...,...,...,...
15670,흥구석유(주),24060,2016/12,7.660000e+00,963788.0,125854.0,NaN,963788.0,125854.0,7.66
15671,흥구석유(주),24060,2017/12,5.910000e+00,751487.0,127191.0,NaN,751487.0,127191.0,5.91
15672,흥구석유(주),24060,2018/12,1.266000e+01,1092436.0,86276.0,NaN,1092436.0,86276.0,12.66
15673,흥구석유(주),24060,2019/12,2.520200e+02,500763.0,1987.0,NaN,500763.0,1987.0,252.02
15674,흥구석유(주),24060,2020/12,1.000000e+09,-493797.0,0.0,NaN,-493797.0,0.0,-inf

In [11]:
df_data[df_data["회사명"]=="(주)금빛"]

,회사명,거래소코드,회계년도,[제조]이자보상배율(이자비용)(IFRS),[제조]* (정상)영업손익(보고서기재)(IFRS),[제조]이자비용(IFRS),[제조]이자보상배율(이자비용)(IFRS연결),[제조]* (정상)영업손익(보고서기재)(IFRS연결),[제조]이자비용(IFRS연결),이자보상배율
240,(주)금빛,45890,2010/12,-3.91,-12641422.0,3232752.0,-3.33,-11185609.0,3359211.0,-3.33
241,(주)금빛,45890,2011/12,-7.50,-23453022.0,3125423.0,-7.72,-28092675.0,3639472.0,-7.72
242,(주)금빛,45890,2012/12,1.58,4426882.0,2802197.0,-1.49,-4298279.0,2886701.0,-1.49
243,(주)금빛,45890,2013/12,1.01,3010298.0,2975097.0,1.83,5386449.0,2938524.0,1.83
244,(주)금빛,45890,2014/12,2.13,5408716.0,2537642.0,2.26,5726835.0,2537809.0,2.26
245,(주)금빛,45890,2015/12,1.85,4332701.0,2346939.0,1.82,4267123.0,2346939.0,1.82
246,(주)금빛,45890,2016/12,1.37,3137611.0,2282499.0,1.83,4166263.0,2282499.0,1.83
247,(주)금빛,45890,2017/12,-1.45,-2981646.0,2049689.0,0.03,59125.0,2049740.0,0.03
248,(주)금빛,45890,2018/12,-9.55,-18191416.0,1905525.0,-8.83,-16869325.0,1909997.0,-8.83
249,(주)금빛,45890,2019/12,-4.23,-16662557.0,3938198.0,-4.07,-16108710.0,3954193.0,-4.07
250,(주)금빛,45890,2020/12,-4.44,-16412470.0,3694783.0,-4.86,-18854001.0,3878491.0,-4.86

In [12]:
df_data_mod = df_data[["회사명","거래소코드","회계년도","이자보상배율"]]
df_data_mod

            회사명  거래소코드     회계년도  이자보상배율
0      (주)CMG제약  58820  2010/12   -7.42
1      (주)CMG제약  58820  2011/12    3.53
2      (주)CMG제약  58820  2012/12   -7.75
3      (주)CMG제약  58820  2013/12    0.70
4      (주)CMG제약  58820  2014/12    3.60
...         ...    ...      ...     ...
15670   흥구석유(주)  24060  2016/12    7.66
15671   흥구석유(주)  24060  2017/12    5.91
15672   흥구석유(주)  24060  2018/12   12.66
15673   흥구석유(주)  24060  2019/12  252.02
15674   흥구석유(주)  24060  2020/12    -inf

[15675 rows x 4 columns]

In [13]:
df_data_mod[df_data_mod["이자보상배율"]==-np.inf]

                 회사명   거래소코드     회계년도  이자보상배율
499    (주)네이블커뮤니케이션즈  153460  2017/12    -inf
500    (주)네이블커뮤니케이션즈  153460  2018/12    -inf
885         (주)대양글로벌   40180  2010/12    -inf
1083         (주)동방선기   99410  2017/12    -inf
1205          (주)듀오백   73190  2018/12    -inf
...              ...     ...      ...     ...
15142     프리시젼바이오(주)  335810  2017/12    -inf
15151         피씨엘(주)  241820  2018/12    -inf
15454      한일네트웍스(주)   46110  2010/12    -inf
15631      휴림네트웍스(주)  192410  2016/12    -inf
15674        흥구석유(주)   24060  2020/12    -inf

[168 rows x 4 columns]

In [14]:
df_data["회계년도"]= pd.to_datetime(df_data["회계년도"])
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15675 entries, 0 to 15674
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   회사명                            15675 non-null  object
 1   거래소코드                          15675 non-null  int64
 2   회계년도                           15675 non-null  datetime64[ns]
 3   [제조]이자보상배율(이자비용)(IFRS)         13374 non-null  float64
 4   [제조]* (정상)영업손익(보고서기재)(IFRS)    13574 non-null  float64
 5   [제조]이자비용(IFRS)                 13574 non-null  float64
 6   [제조]이자보상배율(이자비용)(IFRS연결)       9703 non-null   float64
 7   [제조]* (정상)영업손익(보고서기재)(IFRS연결)  13683 non-null  float64
 8   [제조]이자비용(IFRS연결)               13683 non-null  float64
 9   이자보상배율                         13680 non-null  float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(1)
memory usage: 1.2+ MB

In [15]:
df["회계년도"]= pd.to_datetime(df["회계년도"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9857 entries, 0 to 9856
Data columns (total 55 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   회사명         9857 non-null   object
 1   거래소코드       9857 non-null   int64
 2   회계년도        9857 non-null   datetime64[ns]
 3   상장일         9857 non-null   object
 4   상장폐지일       749 non-null    object
 5   소속코드        9857 non-null   int64
 6   산업명         9857 non-null   object
 7   매출액증가율      9857 non-null   float64
 8   유형자산증가율     9857 non-null   float64
 9   재고자산증가율     9857 non-null   float64
 10  비유동자산증가율    9857 non-null   float64
 11  유동자산증가율     9857 non-null   float64
 12  자기자본증가율     9857 non-null   float64
 13  총자본증가율      9857 non-null   float64
 14  순이익증가율      9857 non-null   float64
 15  매출액총이익률     9857 non-null   float64
 16  매출액순이익률     9857 non-null   float64
 17  자기자본순이익률    9857 non-null   float64
 18  총자본사업이익률    9857 non-null   float64
 19  총자본순이익률     9857 non-null   float64
 20  1주당매출액      9857 non-null   float64
 21  1주당순이익      9857 non-null   float64
 22  유동비율        9857 non-null   float64
 23  당좌비율        9857 non-null   float64
 24  현금비율        9857 non-null   float64
 25  순운전자본비율     9857 non-null   float64
 26  부채비율        9857 non-null   float64
 27  이자보상배율이자비용  9857 non-null   float64
 28  비유동비율       9857 non-null   float64
 29  유동자산구성비율    9857 non-null   float64
 30  자기자본구성비율    9857 non-null   float64
 31  자기자본배율      9857 non-null   float64
 32  총자본회전률      9857 non-null   float64
 33  자기자본회전률     9857 non-null   float64
 34  비유동자산회전률    9857 non-null   float64
 35  재고자산회전률     9857 non-null   float64
 36  매출채권회전률     9857 non-null   float64
 37  매입채무회전률     9857 non-null   float64
 38  매입채무회전기간    9857 non-null   float64
 39  재고자산회전기간    9857 non-null   float64
 40  매출채권회전기간    9857 non-null   float64
 41  1회전기간       9857 non-null   float64
 42  운전자본회전률     9857 non-null   float64
 43  순운전자본회전률    9857 non-null   float64
 44  유형자산회전율     9857 non-null   float64
 45  유동자산회전률     9857 non-null   float64
 46  당좌자산회전률     9857 non-null   float64
 47  부가가치        9857 non-null   float64
 48  총자본투자효율     9857 non-null   float64
 49  설비투자효율      9857 non-null   float64
 50  기계투자효율      9857 non-null   float64
 51  부가가치율       9857 non-null   float64
 52  노동소득분배율     9857 non-null   float64
 53  자본분배율       9857 non-null   float64
 54  이윤분배율       9857 non-null   float64
dtypes: datetime64[ns](1), float64(48), int64(2), object(4)
memory usage: 4.1+ MB

In [16]:
a = pd.merge(df,df_data, how='left',on=["회사명","거래소코드","회계년도"])
a

,회사명,거래소코드,회계년도,상장일,상장폐지일,소속코드,산업명,매출액증가율,유형자산증가율,재고자산증가율,...,노동소득분배율,자본분배율,이윤분배율,[제조]이자보상배율(이자비용)(IFRS),[제조]* (정상)영업손익(보고서기재)(IFRS),[제조]이자비용(IFRS),[제조]이자보상배율(이자비용)(IFRS연결),[제조]* (정상)영업손익(보고서기재)(IFRS연결),[제조]이자비용(IFRS연결),이자보상배율
0,(주)CMG제약,58820,2011-12-01,2001-08-31,NaN,5,의료용 물질 및 의약품 제조업,56.40,-5.90,-1.43,...,89.82,10.18,-43.44,3.940000e+00,714950.0,181404.0,3.53,640283.0,181404.0,3.53
1,(주)CMG제약,58820,2012-12-01,2001-08-31,NaN,5,의료용 물질 및 의약품 제조업,-8.43,-4.12,7.73,...,1749.87,-1649.87,-2473.07,-7.450000e+00,-4045140.0,542880.0,-7.75,-4205503.0,542880.0,-7.75
2,(주)CMG제약,58820,2013-12-01,2001-08-31,NaN,5,의료용 물질 및 의약품 제조업,25.51,16.09,56.29,...,71.28,28.72,4.23,7.300000e-01,822547.0,1133753.0,0.70,791250.0,1134104.0,0.70
3,(주)CMG제약,58820,2014-12-01,2001-08-31,NaN,5,의료용 물질 및 의약품 제조업,11.52,74.30,6.37,...,79.30,20.70,2.24,3.630000e+00,446018.0,122840.0,3.60,442322.0,122840.0,3.60
4,(주)CMG제약,58820,2015-12-01,2001-08-31,NaN,5,의료용 물질 및 의약품 제조업,18.85,-5.37,11.04,...,144.10,-44.10,-84.58,-3.220000e+01,-2570878.0,79830.0,-32.22,-2572168.0,79830.0,-32.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9852,흥구석유(주),24060,2016-12-01,1994-12-07,NaN,5,도매 및 상품 중개업,-7.26,-5.61,52.46,...,44.46,55.54,43.99,7.660000e+00,963788.0,125854.0,NaN,963788.0,125854.0,7.66
9853,흥구석유(주),24060,2017-12-01,1994-12-07,NaN,5,도매 및 상품 중개업,8.12,-0.56,9.41,...,43.35,56.65,43.02,5.910000e+00,751487.0,127191.0,NaN,751487.0,127191.0,5.91
9854,흥구석유(주),24060,2018-12-01,1994-12-07,NaN,5,도매 및 상품 중개업,6.87,-0.36,-46.09,...,46.23,53.77,40.99,1.266000e+01,1092436.0,86276.0,NaN,1092436.0,86276.0,12.66
9855,흥구석유(주),24060,2019-12-01,1994-12-07,NaN,5,도매 및 상품 중개업,-9.35,-7.00,96.40,...,62.14,37.86,27.35,2.520200e+02,500763.0,1987.0,NaN,500763.0,1987.0,252.02
9856,흥구석유(주),24060,2020-12-01,1994-12-07,NaN,5,도매 및 상품 중개업,-23.78,-13.92,-18.61,...,56.12,43.88,34.63,1.000000e+09,-493797.0,0.0,NaN,-493797.0,0.0,-inf

In [17]:
a.columns

Index(['회사명', '거래소코드', '회계년도', '상장일', '상장폐지일', '소속코드', '산업명', '매출액증가율',
       '유형자산증가율', '재고자산증가율', '비유동자산증가율', '유동자산증가율', '자기자본증가율', '총자본증가율',
       '순이익증가율', '매출액총이익률', '매출액순이익률', '자기자본순이익률', '총자본사업이익률', '총자본순이익률',
       '1주당매출액', '1주당순이익', '유동비율', '당좌비율', '현금비율', '순운전자본비율', '부채비율',
       '이자보상배율이자비용', '비유동비율', '유동자산구성비율', '자기자본구성비율', '자기자본배율', '총자본회전률',
       '자기자본회전률', '비유동자산회전률', '재고자산회전률', '매출채권회전률', '매입채무회전률', '매입채무회전기간',
       '재고자산회전기간', '매출채권회전기간', '1회전기간', '운전자본회전률', '순운전자본회전률', '유형자산회전율',
       '유동자산회전률', '당좌자산회전률', '부가가치', '총자본투자효율', '설비투자효율', '기계투자효율', '부가가치율',
       '노동소득분배율', '자본분배율', '이윤분배율', '[제조]이자보상배율(이자비용)(IFRS)',
       '[제조]* (정상)영업손익(보고서기재)(IFRS)', '[제조]이자비용(IFRS)',
       '[제조]이자보상배율(이자비용)(IFRS연결)', '[제조]* (정상)영업손익(보고서기재)(IFRS연결)',
       '[제조]이자비용(IFRS연결)', '이자보상배율'],
      dtype='object')

In [18]:
a[a["회사명"]=="(주)금빛"]

,회사명,거래소코드,회계년도,상장일,상장폐지일,소속코드,산업명,매출액증가율,유형자산증가율,재고자산증가율,...,노동소득분배율,자본분배율,이윤분배율,[제조]이자보상배율(이자비용)(IFRS),[제조]* (정상)영업손익(보고서기재)(IFRS),[제조]이자비용(IFRS),[제조]이자보상배율(이자비용)(IFRS연결),[제조]* (정상)영업손익(보고서기재)(IFRS연결),[제조]이자비용(IFRS연결),이자보상배율
171,(주)금빛,45890,2011-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,-24.64,-3.53,-57.36,...,0.00,0.00,0.00,-7.50,-23453022.0,3125423.0,-7.72,-28092675.0,3639472.0,-7.72
172,(주)금빛,45890,2012-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,27.92,-1.04,-15.85,...,137.85,-37.85,-86.79,1.58,4426882.0,2802197.0,-1.49,-4298279.0,2886701.0,-1.49
173,(주)금빛,45890,2013-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,22.98,-2.39,-14.98,...,61.47,38.53,12.74,1.01,3010298.0,2975097.0,1.83,5386449.0,2938524.0,1.83
174,(주)금빛,45890,2014-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,-6.51,0.15,27.64,...,66.07,33.93,7.02,2.13,5408716.0,2537642.0,2.26,5726835.0,2537809.0,2.26
175,(주)금빛,45890,2015-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,2.58,-0.20,0.30,...,63.79,36.21,12.95,1.85,4332701.0,2346939.0,1.82,4267123.0,2346939.0,1.82
176,(주)금빛,45890,2016-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,-10.77,-2.69,-13.78,...,63.14,36.86,11.76,1.37,3137611.0,2282499.0,1.83,4166263.0,2282499.0,1.83
177,(주)금빛,45890,2017-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,-3.64,-2.67,16.97,...,84.22,15.78,-32.44,-1.45,-2981646.0,2049689.0,0.03,59125.0,2049740.0,0.03
178,(주)금빛,45890,2018-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,-27.08,37.83,-22.62,...,139.63,-39.63,-64.80,-9.55,-18191416.0,1905525.0,-8.83,-16869325.0,1909997.0,-8.83
179,(주)금빛,45890,2019-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,10.33,2.58,-23.16,...,0.00,0.00,0.00,-4.23,-16662557.0,3938198.0,-4.07,-16108710.0,3954193.0,-4.07
180,(주)금빛,45890,2020-12-01,2005-11-28,2021-12-20,4,전기장비 제조업,-30.22,8.74,-51.27,...,4117.38,-4017.38,-6527.69,-4.44,-16412470.0,3694783.0,-4.86,-18854001.0,3878491.0,-4.86

In [19]:
df_mod = a[['회사명', '거래소코드', '회계년도', '상장일', '상장폐지일', '소속코드','이자보상배율','이자보상배율이자비용']]
df_mod

           회사명  거래소코드       회계년도         상장일 상장폐지일  소속코드  이자보상배율  이자보상배율이자비용
0     (주)CMG제약  58820 2011-12-01  2001-08-31   NaN     5    3.53        3.53
1     (주)CMG제약  58820 2012-12-01  2001-08-31   NaN     5   -7.75       -7.75
2     (주)CMG제약  58820 2013-12-01  2001-08-31   NaN     5    0.70        0.70
3     (주)CMG제약  58820 2014-12-01  2001-08-31   NaN     5    3.60        3.60
4     (주)CMG제약  58820 2015-12-01  2001-08-31   NaN     5  -32.22      -32.22
...        ...    ...        ...         ...   ...   ...     ...         ...
9852   흥구석유(주)  24060 2016-12-01  1994-12-07   NaN     5    7.66      172.77
9853   흥구석유(주)  24060 2017-12-01  1994-12-07   NaN     5    5.91      208.21
9854   흥구석유(주)  24060 2018-12-01  1994-12-07   NaN     5   12.66      301.30
9855   흥구석유(주)  24060 2019-12-01  1994-12-07   NaN     5  252.02      131.90
9856   흥구석유(주)  24060 2020-12-01  1994-12-07   NaN     5    -inf       34.51

[9857 rows x 8 columns]

In [20]:
df_mod[df_mod["회사명"]=="(주)금빛"]

       회사명  거래소코드       회계년도         상장일       상장폐지일  소속코드  이자보상배율  이자보상배율이자비용
171  (주)금빛  45890 2011-12-01  2005-11-28  2021-12-20     4   -7.72       -7.72
172  (주)금빛  45890 2012-12-01  2005-11-28  2021-12-20     4   -1.49       -1.49
173  (주)금빛  45890 2013-12-01  2005-11-28  2021-12-20     4    1.83        1.83
174  (주)금빛  45890 2014-12-01  2005-11-28  2021-12-20     4    2.26        2.26
175  (주)금빛  45890 2015-12-01  2005-11-28  2021-12-20     4    1.82        1.82
176  (주)금빛  45890 2016-12-01  2005-11-28  2021-12-20     4    1.83        1.83
177  (주)금빛  45890 2017-12-01  2005-11-28  2021-12-20     4    0.03        0.03
178  (주)금빛  45890 2018-12-01  2005-11-28  2021-12-20     4   -8.83       -8.83
179  (주)금빛  45890 2019-12-01  2005-11-28  2021-12-20     4   -4.07       -4.07
180  (주)금빛  45890 2020-12-01  2005-11-28  2021-12-20     4   -4.86       -4.86

In [21]:
df_mod_0 = df_mod[df_mod["상장폐지일"].isnull()]
df_mod_0

           회사명  거래소코드       회계년도         상장일 상장폐지일  소속코드  이자보상배율  이자보상배율이자비용
0     (주)CMG제약  58820 2011-12-01  2001-08-31   NaN     5    3.53        3.53
1     (주)CMG제약  58820 2012-12-01  2001-08-31   NaN     5   -7.75       -7.75
2     (주)CMG제약  58820 2013-12-01  2001-08-31   NaN     5    0.70        0.70
3     (주)CMG제약  58820 2014-12-01  2001-08-31   NaN     5    3.60        3.60
4     (주)CMG제약  58820 2015-12-01  2001-08-31   NaN     5  -32.22      -32.22
...        ...    ...        ...         ...   ...   ...     ...         ...
9852   흥구석유(주)  24060 2016-12-01  1994-12-07   NaN     5    7.66      172.77
9853   흥구석유(주)  24060 2017-12-01  1994-12-07   NaN     5    5.91      208.21
9854   흥구석유(주)  24060 2018-12-01  1994-12-07   NaN     5   12.66      301.30
9855   흥구석유(주)  24060 2019-12-01  1994-12-07   NaN     5  252.02      131.90
9856   흥구석유(주)  24060 2020-12-01  1994-12-07   NaN     5    -inf       34.51

[9108 rows x 8 columns]

In [22]:
df_mod_0[df_mod_0["이자보상배율"].isin([np.NaN,np.inf,-np.inf])]

,회사명,거래소코드,회계년도,상장일,상장폐지일,소속코드,이자보상배율,이자보상배율이자비용
5,(주)CMG제약,58820,2016-12-01,2001-08-31,NaN,5,inf,1.000000e+09
6,(주)CMG제약,58820,2017-12-01,2001-08-31,NaN,5,inf,1.000000e+09
7,(주)CMG제약,58820,2018-12-01,2001-08-31,NaN,5,inf,1.000000e+09
181,(주)금화피에스시,36190,2012-12-01,2000-12-26,NaN,5,inf,4.165200e+02
240,(주)나스미디어,89600,2014-12-01,2013-07-17,NaN,5,inf,-4.420000e+00
...,...,...,...,...,...,...,...,...
9791,현대에이치티(주),39010,2019-12-01,2000-07-20,NaN,5,inf,2.009000e+01
9825,휴림네트웍스(주),192410,2015-12-01,2014-08-14,NaN,5,inf,1.000000e+09
9826,휴림네트웍스(주),192410,2016-12-01,2014-08-14,NaN,5,-inf,1.000000e+09
9842,휴젤(주),145020,2016-12-01,2015-12-24,NaN,5,inf,1.000000e+09
9856,흥구석유(주),24060,2020-12-01,1994-12-07,NaN,5,-inf,3.451000e+01

In [23]:
df_mod_0_0 =df_mod_0[~df_mod_0["이자보상배율"].isin([np.NaN,np.inf,-np.inf])]
df_mod_0_0.describe()

              거래소코드         소속코드        이자보상배율    이자보상배율이자비용
count    8555.00000  8555.000000  8.555000e+03  8.555000e+03
mean    79269.87142     5.041029  1.631204e+03  1.636838e+07
std     59764.84106     0.203603  1.221657e+05  1.268805e+08
min       250.00000     4.000000 -4.493653e+06 -1.092159e+05
25%     38530.00000     5.000000 -5.750000e-01 -4.750000e-01
50%     64520.00000     5.000000  3.350000e+00  3.470000e+00
75%     99320.00000     5.000000  2.043000e+01  2.181000e+01
max    327260.00000     6.000000  8.432098e+06  1.000000e+09

In [24]:
df_mod_0_0["이자보상배율"].max()
df_mod_0_0["이자보상배율"].min()

-4493653.0

In [25]:
df_mod[df_mod["상장폐지일"].isnull()][df_mod_0["상장폐지일"].isnull()]["이자보상배율"]

0         3.53
1        -7.75
2         0.70
3         3.60
4       -32.22
         ...
9852      7.66
9853      5.91
9854     12.66
9855    252.02
9856      -inf
Name: 이자보상배율, Length: 9108, dtype: float64

In [26]:
df_mod_1 = df_mod[~df_mod["상장폐지일"].isnull()]
df_mod_1

,회사명,거래소코드,회계년도,상장일,상장폐지일,소속코드,이자보상배율,이자보상배율이자비용
171,(주)금빛,45890,2011-12-01,2005-11-28,2021-12-20,4,-7.72,-7.72
172,(주)금빛,45890,2012-12-01,2005-11-28,2021-12-20,4,-1.49,-1.49
173,(주)금빛,45890,2013-12-01,2005-11-28,2021-12-20,4,1.83,1.83
174,(주)금빛,45890,2014-12-01,2005-11-28,2021-12-20,4,2.26,2.26
175,(주)금빛,45890,2015-12-01,2005-11-28,2021-12-20,4,1.82,1.82
...,...,...,...,...,...,...,...,...
9807,현진소재(주),53660,2016-12-01,2002-02-15,2022-04-26,4,0.87,8.04
9808,현진소재(주),53660,2017-12-01,2002-02-15,2022-04-26,4,-0.77,10.87
9809,현진소재(주),53660,2018-12-01,2002-02-15,2022-04-26,4,-2.42,-2.42
9810,현진소재(주),53660,2019-12-01,2002-02-15,2022-04-26,4,-4.57,-4.57
9811,현진소재(주),53660,2020-12-01,2002-02-15,2022-04-26,4,-5.93,-5.93

In [27]:
df_mod_1[df_mod_1["이자보상배율"].isin([np.NaN,np.inf,-np.inf])]

,회사명,거래소코드,회계년도,상장일,상장폐지일,소속코드,이자보상배율,이자보상배율이자비용
351,(주)넥스지,81970,2011-12-01,2007-08-20,2018-10-11,4,inf,9.470000e+00
353,(주)넥스지,81970,2013-12-01,2007-08-20,2018-10-11,4,inf,1.000000e+09
1298,(주)모린스,110310,2013-12-01,2009-09-25,2014-04-11,4,-inf,1.000000e+09
1364,(주)미래테크놀로지,213090,2017-12-01,2015-12-01,2021-10-05,4,inf,1.000000e+09
1368,(주)미성포리테크,94700,2011-12-01,2007-12-20,2012-04-13,4,-inf,1.000000e+09
1560,(주)블루젬디앤씨,53040,2011-12-01,2001-08-09,2012-05-17,4,inf,1.000000e+09
1735,(주)삼우이엠씨,26250,2012-12-01,1995-11-04,2013-04-12,4,-inf,1.000000e+09
2042,(주)세영디앤씨,52190,2011-12-01,2001-06-21,2022-05-27,4,inf,-3.740000e+00
2043,(주)세영디앤씨,52190,2012-12-01,2001-06-21,2022-05-27,4,-inf,2.910000e+00
2044,(주)세영디앤씨,52190,2014-12-01,2001-06-21,2022-05-27,4,-inf,1.778000e+01
2045,(주)세영디앤씨,52190,2015-12-01,2001-06-21,2022-05-27,4,-inf,-1.738400e+02
2046,(주)세영디앤씨,52190,2016-12-01,2001-06-21,2022-05-27,4,-inf,-1.574000e+01
2595,(주)씨티앤티,50470,2011-12-01,2002-04-23,2012-05-01,4,-inf,2.730000e+00
3099,(주)에스에스컴텍,36500,2016-12-01,1999-12-14,2017-05-11,4,-inf,1.000000e+09
3651,(주)엘엑스세미콘,108320,2012-12-01,2010-06-08,2022-11-03,4,inf,1.000000e+09
3652,(주)엘엑스세미콘,108320,2013-12-01,2010-06-08,2022-11-03,4,inf,1.000000e+09
3653,(주)엘엑스세미콘,108320,2014-12-01,2010-06-08,2022-11-03,4,inf,1.000000e+09
3654,(주)엘엑스세미콘,108320,2015-12-01,2010-06-08,2022-11-03,4,inf,1.000000e+09
3655,(주)엘엑스세미콘,108320,2016-12-01,2010-06-08,2022-11-03,4,inf,1.000000e+09
3656,(주)엘엑스세미콘,108320,2017-12-01,2010-06-08,2022-11-03,4,inf,1.000000e+09
3657,(주)엘엑스세미콘,108320,2018-12-01,2010-06-08,2022-11-03,4,inf,1.000000e+09
3989,(주)와이즈파워,40670,2011-12-01,2000-08-18,2015-07-16,4,-inf,1.000000e+09
3990,(주)와이즈파워,40670,2012-12-01,2000-08-18,2015-07-16,4,-inf,1.000000e+09
4049,(주)우전,52270,2011-12-01,2001-06-05,2017-04-13,4,inf,1.000000e+09
5168,(주)지앤에스티,36920,2012-12-01,1999-12-21,2013-05-07,4,inf,5.900000e-01
5795,(주)코아에스앤아이,52350,2011-12-01,2001-07-20,2012-04-17,4,-inf,-3.550000e+00
6384,(주)팍스넷,38160,2017-12-01,2016-08-01,2021-08-23,4,inf,2.756000e+01
7275,넥슨지티(주),41140,2013-12-01,2000-07-25,2022-04-15,4,inf,3.770000e+00
7276,넥슨지티(주),41140,2014-12-01,2000-07-25,2022-04-15,4,inf,4.590000e+00
7277,넥슨지티(주),41140,2015-12-01,2000-07-25,2022-04-15,4,inf,8.720000e+00
7278,넥슨지티(주),41140,2016-12-01,2000-07-25,2022-04-15,4,inf,1.000000e+09

In [28]:
df_mod_1_1 =df_mod_1[~df_mod_1["이자보상배율"].isin([np.NaN,np.inf,-np.inf])]
df_mod_1_1.describe()

               거래소코드   소속코드        이자보상배율    이자보상배율이자비용
count     718.000000  718.0    718.000000  7.180000e+02
mean    73878.384401    4.0     30.509666  2.228812e+07
std     50345.922236    0.0   1926.923071  1.477084e+08
min      2670.000000    4.0 -17335.030000 -1.738423e+04
25%     38160.000000    4.0     -5.360000 -4.602500e+00
50%     60300.000000    4.0     -1.580000 -1.100000e+00
75%     91690.000000    4.0      1.645000  2.650000e+00
max    290510.000000    4.0  44552.040000  1.000000e+09

In [29]:
df_mod[~df_mod["상장폐지일"].isnull()]["이자보상배율"]

171    -7.72
172    -1.49
173     1.83
174     2.26
175     1.82
        ...
9807    0.87
9808   -0.77
9809   -2.42
9810   -4.57
9811   -5.93
Name: 이자보상배율, Length: 749, dtype: float64

In [30]:
df_mod

           회사명  거래소코드       회계년도         상장일 상장폐지일  소속코드  이자보상배율  이자보상배율이자비용
0     (주)CMG제약  58820 2011-12-01  2001-08-31   NaN     5    3.53        3.53
1     (주)CMG제약  58820 2012-12-01  2001-08-31   NaN     5   -7.75       -7.75
2     (주)CMG제약  58820 2013-12-01  2001-08-31   NaN     5    0.70        0.70
3     (주)CMG제약  58820 2014-12-01  2001-08-31   NaN     5    3.60        3.60
4     (주)CMG제약  58820 2015-12-01  2001-08-31   NaN     5  -32.22      -32.22
...        ...    ...        ...         ...   ...   ...     ...         ...
9852   흥구석유(주)  24060 2016-12-01  1994-12-07   NaN     5    7.66      172.77
9853   흥구석유(주)  24060 2017-12-01  1994-12-07   NaN     5    5.91      208.21
9854   흥구석유(주)  24060 2018-12-01  1994-12-07   NaN     5   12.66      301.30
9855   흥구석유(주)  24060 2019-12-01  1994-12-07   NaN     5  252.02      131.90
9856   흥구석유(주)  24060 2020-12-01  1994-12-07   NaN     5    -inf       34.51

[9857 rows x 8 columns]

In [31]:
for i in df_mod.index:
    if df_mod.loc[i,"이자보상배율"] == np.inf and df_mod.loc[i,"상장폐지일"] ==np.NaN:
        df_mod.loc[i,"이자보상배율"] = df_mod_0_0["이자보상배율"].max()

    elif df_mod.loc[i,"이자보상배율"] == -np.inf and df_mod.loc[i,"상장폐지일"] ==np.NaN:
        df_mod.loc[i,"이자보상배율"] = df_mod_0_0["이자보상배율"].min()

    elif df_mod.loc[i,"이자보상배율"] == np.NaN and df_mod.loc[i,"상장폐지일"] ==np.NaN:
        df_mod.loc[i,"이자보상배율"] = df_mod_0_0["이자보상배율"].mean()

    elif df_mod.loc[i,"이자보상배율"] == np.inf and df_mod.loc[i,"상장폐지일"] !=np.NaN:
        df_mod.loc[i,"이자보상배율"] = df_mod_1_1["이자보상배율"].max()

    elif df_mod.loc[i,"이자보상배율"] == -np.inf and df_mod.loc[i,"상장폐지일"] !=np.NaN:
        df_mod.loc[i,"이자보상배율"] = df_mod_1_1["이자보상배율"].min()

    elif df_mod.loc[i,"이자보상배율"] == np.NaN and df_mod.loc[i,"상장폐지일"] !=np.NaN:
        df_mod.loc[i,"이자보상배율"] = df_mod_1_1["이자보상배율"].mean()

In [32]:
df_mod[df_mod["상장폐지일"].isnull()]["이자보상배율"]

0           3.53
1          -7.75
2           0.70
3           3.60
4         -32.22
          ...
9852        7.66
9853        5.91
9854       12.66
9855      252.02
9856   -17335.03
Name: 이자보상배율, Length: 9108, dtype: float64

In [33]:
df_mod.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9857 entries, 0 to 9856
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   회사명         9857 non-null   object
 1   거래소코드       9857 non-null   int64
 2   회계년도        9857 non-null   datetime64[ns]
 3   상장일         9857 non-null   object
 4   상장폐지일       749 non-null    object
 5   소속코드        9857 non-null   int64
 6   이자보상배율      9857 non-null   float64
 7   이자보상배율이자비용  9857 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(3)
memory usage: 951.1+ KB

In [34]:
df_mod

           회사명  거래소코드       회계년도         상장일 상장폐지일  소속코드    이자보상배율  이자보상배율이자비용
0     (주)CMG제약  58820 2011-12-01  2001-08-31   NaN     5      3.53        3.53
1     (주)CMG제약  58820 2012-12-01  2001-08-31   NaN     5     -7.75       -7.75
2     (주)CMG제약  58820 2013-12-01  2001-08-31   NaN     5      0.70        0.70
3     (주)CMG제약  58820 2014-12-01  2001-08-31   NaN     5      3.60        3.60
4     (주)CMG제약  58820 2015-12-01  2001-08-31   NaN     5    -32.22      -32.22
...        ...    ...        ...         ...   ...   ...       ...         ...
9852   흥구석유(주)  24060 2016-12-01  1994-12-07   NaN     5      7.66      172.77
9853   흥구석유(주)  24060 2017-12-01  1994-12-07   NaN     5      5.91      208.21
9854   흥구석유(주)  24060 2018-12-01  1994-12-07   NaN     5     12.66      301.30
9855   흥구석유(주)  24060 2019-12-01  1994-12-07   NaN     5    252.02      131.90
9856   흥구석유(주)  24060 2020-12-01  1994-12-07   NaN     5 -17335.03       34.51

[9857 rows x 8 columns]

In [35]:
df["이자보상배율이자비용"] = df_mod["이자보상배율"]
df["이자보상배율이자비용"]

0           3.53
1          -7.75
2           0.70
3           3.60
4         -32.22
          ...
9852        7.66
9853        5.91
9854       12.66
9855      252.02
9856   -17335.03
Name: 이자보상배율이자비용, Length: 9857, dtype: float64

In [36]:
df[df["이자보상배율이자비용"].isin([np.NaN,np.inf,-np.inf])]

Empty DataFrame
Columns: [회사명, 거래소코드, 회계년도, 상장일, 상장폐지일, 소속코드, 산업명, 매출액증가율, 유형자산증가율, 재고자산증가율, 비유동자산증가율, 유동자산증가율, 자기자본증가율, 총자본증가율, 순이익증가율, 매출액총이익률, 매출액순이익률, 자기자본순이익률, 총자본사업이익률, 총자본순이익률, 1주당매출액, 1주당순이익, 유동비율, 당좌비율, 현금비율, 순운전자본비율, 부채비율, 이자보상배율이자비용, 비유동비율, 유동자산구성비율, 자기자본구성비율, 자기자본배율, 총자본회전률, 자기자본회전률, 비유동자산회전률, 재고자산회전률, 매출채권회전률, 매입채무회전률, 매입채무회전기간, 재고자산회전기간, 매출채권회전기간, 1회전기간, 운전자본회전률, 순운전자본회전률, 유형자산회전율, 유동자산회전률, 당좌자산회전률, 부가가치, 총자본투자효율, 설비투자효율, 기계투자효율, 부가가치율, 노동소득분배율, 자본분배율, 이윤분배율]
Index: []

[0 rows x 55 columns]

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9857 entries, 0 to 9856
Data columns (total 55 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   회사명         9857 non-null   object
 1   거래소코드       9857 non-null   int64
 2   회계년도        9857 non-null   datetime64[ns]
 3   상장일         9857 non-null   object
 4   상장폐지일       749 non-null    object
 5   소속코드        9857 non-null   int64
 6   산업명         9857 non-null   object
 7   매출액증가율      9857 non-null   float64
 8   유형자산증가율     9857 non-null   float64
 9   재고자산증가율     9857 non-null   float64
 10  비유동자산증가율    9857 non-null   float64
 11  유동자산증가율     9857 non-null   float64
 12  자기자본증가율     9857 non-null   float64
 13  총자본증가율      9857 non-null   float64
 14  순이익증가율      9857 non-null   float64
 15  매출액총이익률     9857 non-null   float64
 16  매출액순이익률     9857 non-null   float64
 17  자기자본순이익률    9857 non-null   float64
 18  총자본사업이익률    9857 non-null   float64
 19  총자본순이익률     9857 non-null   float64
 20  1주당매출액      9857 non-null   float64
 21  1주당순이익      9857 non-null   float64
 22  유동비율        9857 non-null   float64
 23  당좌비율        9857 non-null   float64
 24  현금비율        9857 non-null   float64
 25  순운전자본비율     9857 non-null   float64
 26  부채비율        9857 non-null   float64
 27  이자보상배율이자비용  9857 non-null   float64
 28  비유동비율       9857 non-null   float64
 29  유동자산구성비율    9857 non-null   float64
 30  자기자본구성비율    9857 non-null   float64
 31  자기자본배율      9857 non-null   float64
 32  총자본회전률      9857 non-null   float64
 33  자기자본회전률     9857 non-null   float64
 34  비유동자산회전률    9857 non-null   float64
 35  재고자산회전률     9857 non-null   float64
 36  매출채권회전률     9857 non-null   float64
 37  매입채무회전률     9857 non-null   float64
 38  매입채무회전기간    9857 non-null   float64
 39  재고자산회전기간    9857 non-null   float64
 40  매출채권회전기간    9857 non-null   float64
 41  1회전기간       9857 non-null   float64
 42  운전자본회전률     9857 non-null   float64
 43  순운전자본회전률    9857 non-null   float64
 44  유형자산회전율     9857 non-null   float64
 45  유동자산회전률     9857 non-null   float64
 46  당좌자산회전률     9857 non-null   float64
 47  부가가치        9857 non-null   float64
 48  총자본투자효율     9857 non-null   float64
 49  설비투자효율      9857 non-null   float64
 50  기계투자효율      9857 non-null   float64
 51  부가가치율       9857 non-null   float64
 52  노동소득분배율     9857 non-null   float64
 53  자본분배율       9857 non-null   float64
 54  이윤분배율       9857 non-null   float64
dtypes: datetime64[ns](1), float64(48), int64(2), object(4)
memory usage: 4.1+ MB

In [38]:
df.to_csv("./데이터자료/5. 이자보상배율 완료.csv",encoding='cp949',index=False)